# frozen_string_literal: true

source "https://rubygems.org"

# Rails
gem "rails", "~> 8.0.0"

# Database
gem "pg", "~> 1.5"

# Web server
gem "puma", "~> 6.5"

# Assets
gem "propshaft"
gem "importmap-rails"
gem "tailwindcss-rails"

# Hotwire
gem "turbo-rails"
gem "stimulus-rails"

# Security
gem "bcrypt", "~> 3.1.7"

# Holidays
gem "holiday_jp"

# Image processing (Active Storage)
gem "image_processing", "~> 1.2"

# Timezone
gem "tzinfo-data", platforms: %i[windows jruby]

# Performance
gem "bootsnap", require: false

group :development do
  gem "web-console"
end
